spring.datasource.url=jdbc:mysql://mysql-service:3306/devopsdb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


server.port=${PORT:8089}

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
jwt.secret=ThisIsMySuperSecretKeyForJwtToken12345
jwt.expiration=86400000

# email-service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fs8377105@gmail.com
spring.mail.password=vfqubnzjcicckmad
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Payment Service

razorpay.key= rzp_test_SITac4XGrv2JpD
razorpay.secret=cBbKHOjyiYV6rME0q2ijnCZ1

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.hibernate.ddl-auto=update

cloudinary.cloud_name=dumkbmgjn
cloudinary.api_key=192361156512316
cloudinary.api_secret=hitH2Rj5EuvdSJ6m1-w3OT9jSkM